site_name: ゼロから学ぶ C++
site_description: ゼロから学ぶ C++
site_author: 井田 献一朗
site_url: http://rinatz.github.io/cpp-book
repo_name: rinatz/cpp-book
repo_url: https://github.com/rinatz/cpp-book
copyright: Copyright &copy 2019 Kenichiro IDA

theme:
  name: material
  language: ja
  logo: img/cpp.svg
  palette:
    primary: indigo
    accent: amber
  font:
    text: Noto Sans
    code: Inconsolata

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmate

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - ホーム: index.md
  - 1. C++ を始める:
      - 1.1. インストール: ch01-01-installation.md
      - 1.2. Hello, World!: ch01-02-hello-world.md
  - 2. 基本構文:
      - 2.1. 変数: ch02-01-variables.md
      - 2.2. 基本型: ch02-02-primitive-types.md
      - 2.3. ポインタ: ch02-03-pointers.md
      - 2.4. コメント: ch02-04-comments.md
      - 2.5. 制御文: ch02-05-control-flow.md
  - 3. コンテナ:
      - 3.1. 配列: ch03-01-arrays.md
      - 3.2. 文字列: ch03-02-strings.md
      - 3.3. タプル: ch03-03-tuples.md
      - 3.4. ベクタ: ch03-04-vectors.md
      - 3.5. リスト: ch03-05-lists.md
